### ISSUE TITLE
a2j_control syntax uses --start instead of just start like all others

### ISSUE THREAD

**Issue by tartina** [linuxaudio/a2jmidid#9]
This problem was reported in Fedora 32 (https://bugzilla.redhat.com/show_bug.cgi?id=1822206).
Fedora 32 is the first Fedora version to ship this fork of a2jmidid.

Changing start to --start breaks some convention in starting dbus services.
Can we restore old behavior, or add some compatibility switches?

**Comment by dvzrv** [comment]
> Changing start to --start breaks some convention in starting dbus services.

Could you elaborate on what that convention is?

> Can we restore old behavior, or add some compatibility switches?

What would be the reason to change this again? Is this hardwired into something that requires these exact parameters?
In theory this can be changed (again), but also leads to many subcommands added. I can look into that, but am not sure when I will have time for this in the coming weeks.

From the downstream bug report:
> a2j_control syntax is not coherent with the rest of the system

What does this mean?

**Comment by tartina** [comment]
I reported your questions to the bug reporter, I can't explain what the rest of the system means too.

**Comment by Stemby** [comment]
I think this issue might be closed like in the downstream bug report.

**Comment by nedko** [comment]
@dvzrv IMO the existing convention is to not use "--verb" but "verb". I.e. "/etc/init.d/myservicename start", "jack_control start", "ladish_control start", "systemctl nginx start".
